[package]
name = "build_the_gate"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_egui = { workspace = true }
bevy_renet = { workspace = true }

debug_info = { path = "../feature/debug_info" }
key_bindings = { path = "../feature/key_bindings" }
